### ISSUE TITLE
Constant error Please help 

### ISSUE THREAD

**Issue by ghost** [centrabot/centra#1]
Error: TypeError: Cannot read property 'adminRoles' of null

**Comment by ghost** [comment]
# Also running `TSC` provides these errors

node_modules/mongodb/mongodb.d.ts:5219:89 - error TS2344: Type 'Flatten<TSchema[key]>' does not satisfy the constraint '{ _id?: any; }'.
  Type 'unknown' is not assignable to type '{ _id?: any; }'.
    Type 'Flatten<TSchema[KeysOfAType<TSchema, readonly any[] | undefined>]>' is not assignable to type '{ _id?: any; }'.
      Type 'unknown' is not assignable to type '{ _id?: any; }'.
        Type 'Flatten<TSchema[NonNullable<TSchema[keyof TSchema]> extends readonly any[] | undefined ? keyof TSchema : never]>' is not assignable to type '{ _id?: any; }'.
          Type 'unknown' is not assignable to type '{ _id?: any; }'.
            Type 'Flatten<TSchema[keyof TSchema]>' is not assignable to type '{ _id?: any; }'.
              Type 'unknown' is not assignable to type '{ _id?: any; }'.
                Type 'Flatten<TSchema[string | number | symbol]>' is not assignable to type '{ _id?: any; }'.
                  Type 'unknown' is not assignable to type '{ _id?: any; }'.
                    Type 'Flatten<TSchema[string]> | Flatten<TSchema[number]> | Flatten<TSchema[symbol]>' is not assignable to type '{ _id?: any; }'.
                      Type 'Flatten<TSchema[string]>' is not assignable to type '{ _id?: any; }'.
                        Type 'unknown' is not assignable to type '{ _id?: any; }'.

5219     readonly [key in KeysOfAType<TSchema, ReadonlyArray<any> | undefined>]?: OptionalId<Flatten<TSchema[key]>> | AddToSetOperators<Array<OptionalId<Flatten<TSchema[key]>>>>;
                                                                                             ~~~~~~~~~~~~~~~~~~~~~

node_modules/mongodb/mongodb.d.ts:5219:149 - error TS2344: Type 'Flatten<TSchema[key]>' does not satisfy the constraint '{ _id?: any; }'.

5219     readonly [key in KeysOfAType<TSchema, ReadonlyArray<any> | undefined>]?: OptionalId<Flatten<TSchema[key]>> | AddToSetOperators<Array<OptionalId<Flatten<TSchema[key]>>>>;
                                                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~

node_modules/revolt.js/dist/api/routes.d.ts:8:19 - error TS2305: Module '"revolt-api/types/Auth"' has no exported member 'SessionInfo'.

8 import { Account, SessionInfo } from 'revolt-api/types/Auth';
                    ~~~~~~~~~~~

[2:55:30 AM] Found 3 errors. Watching for file changes.

**Comment by ghost** [comment]
@ThatTonybo

**Comment by ThatTonybo** [comment]
Hi, the bot's currently unfunctional due to library issues, I can't provide any help due to that.

**Comment by ghost** [comment]
oh bummer okay
